### ISSUE TITLE
version

### ISSUE THREAD

**Issue by dmd** [waa/baculabackupreport#8]
https://github.com/waa/baculabackupreport/blob/72c3209f390397f19d94b3a48b683202035f0286/baculabackupreport.py#L4

This is not, in fact, version 1.0, nor is that the release date.

**Comment by waa** [comment]
Hello Daniel,

While `git log` shows that the information in that line is indeed true/correct, you are right, it does not belong in the script there. Every time I see it it bothers me too.

I'll modify it to more clearly show that the initial release was on that date and remove the version 1.0 too.

Thanks for the comment. :)
